name: Feature Request
description: Propose a feature
labels: ["enhancement"]
body:
  - type: dropdown
    id: scope
    attributes:
      label: Scope
      options:
        - Discover phase
        - Comply phase (RGPD/RGS)
        - Secure phase
        - New compliance framework
        - Scripts
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem does this solve?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
    validations:
      required: true

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I'm willing to implement this
