name: 📦 Ingest

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  ingest-codebase:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@f7ccc83f9ed1e5b9c81d8a67d7ad1a747e22a561 # master
        with:
          toolchain: stable

      - name: Build OSK CLI
        run: |
          cd cli
          cargo build --release

      - name: Generate Output Filename
        run: |
          REPO_NAME="${GITHUB_REPOSITORY#*/}"
          CURRENT_DATE=$(date +'%Y-%m-%d')

          if git describe --tags --exact-match >/dev/null 2>&1; then
            VERSION=$(git describe --tags --exact-match)
            FINAL_NAME="context-${REPO_NAME}-${VERSION}-${CURRENT_DATE}.txt"
          else
            SHORT_SHA=$(git rev-parse --short HEAD)
            FINAL_NAME="context-${REPO_NAME}-${SHORT_SHA}-${CURRENT_DATE}.txt"
          fi

          echo "CTX_FILENAME=$FINAL_NAME" >> $GITHUB_ENV

      - name: Run Ingest
        run: |
          ./cli/target/release/osk ingest -p . -o ${{ env.CTX_FILENAME }}

      - name: Upload Ingest Artifact
        uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4.6.0
        with:
          name: ${{ env.CTX_FILENAME }}
          path: ${{ env.CTX_FILENAME }}
          retention-days: 5
